<a href="https://colab.research.google.com/github/Dhruthiya/Nasscom/blob/main/Assignment_EV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1 — Analysis Using Python Basics
Store the given sensor readings using appropriate Python data structures, then perform the following tasks.
1. Display the sensor readings

2. Identify high temperature

3. Identify low battery

4. Create a function
Create a function battery_status(charge)


In [36]:
combined_sensor_data = [
    {"Time": 0, "Temperature": 32, "Voltage": 400, "Current": 20, "Charge": 95},
    {"Time": 1, "Temperature": 35, "Voltage": 395, "Current": 22, "Charge": 88},
    {"Time": 2, "Temperature": 38, "Voltage": 390, "Current": 25, "Charge": 80},
    {"Time": 3, "Temperature": 40, "Voltage": 385, "Current": 28, "Charge": 70},
    {"Time": 4, "Temperature": 42, "Voltage": 380, "Current": 30, "Charge": 60},
    {"Time": 5, "Temperature": 45, "Voltage": 375, "Current": 32, "Charge": 48}
]


In [37]:
print("Task 1: Display all battery readings")
for reading in combined_sensor_data:
    print(f"Battery Charge: {reading['Charge']}%")


Task 1: Display all battery readings
Battery Charge: 95%
Battery Charge: 88%
Battery Charge: 80%
Battery Charge: 70%
Battery Charge: 60%
Battery Charge: 48%


In [38]:
print("\nTask 2: Identify high temperature")
for reading in combined_sensor_data:
    temperature = reading['Temperature']
    if temperature > 40:
        print(f"Time: {reading['Time']}h, Temperature: {temperature}°C - High Temperature Alert")
    else:
        print(f"Time: {reading['Time']}h, Temperature: {temperature}°C - Temperature Normal")



Task 2: Identify high temperature
Time: 0h, Temperature: 32°C - Temperature Normal
Time: 1h, Temperature: 35°C - Temperature Normal
Time: 2h, Temperature: 38°C - Temperature Normal
Time: 3h, Temperature: 40°C - Temperature Normal
Time: 4h, Temperature: 42°C - High Temperature Alert
Time: 5h, Temperature: 45°C - High Temperature Alert


In [39]:
print("\nTask 3: Identify low battery")
for reading in combined_sensor_data:
    charge = reading['Charge']
    if charge < 50:
        print(f"Time: {reading['Time']}h, Charge: {charge}% - Low Battery Alert")
    else:
        print(f"Time: {reading['Time']}h, Charge: {charge}% - Battery Charge Normal")



Task 3: Identify low battery
Time: 0h, Charge: 95% - Battery Charge Normal
Time: 1h, Charge: 88% - Battery Charge Normal
Time: 2h, Charge: 80% - Battery Charge Normal
Time: 3h, Charge: 70% - Battery Charge Normal
Time: 4h, Charge: 60% - Battery Charge Normal
Time: 5h, Charge: 48% - Low Battery Alert


In [40]:
print("\nTask 4: Create battery_status function")
def battery_status(charge):
    if charge > 70:
        return "High"
    elif 50 <= charge <= 70:
        return "Medium"
    else:
        return "Low"


print(f"Battery status for 95%: {battery_status(95)}")
print(f"Battery status for 88%: {battery_status(88)}")
print(f"Battery status for 80%: {battery_status(80)}")
print(f"Battery status for 70%: {battery_status(70)}")
print(f"Battery status for 60%: {battery_status(60)}")
print(f"Battery status for 48%: {battery_status(48)}")



Task 4: Create battery_status function
Battery status for 95%: High
Battery status for 88%: High
Battery status for 80%: High
Battery status for 70%: Medium
Battery status for 60%: Medium
Battery status for 48%: Low


Task 2 — Analysis Using NumPy
Convert the battery data into a NumPy array. Assume the data matrix is:
Perform the following operations:
1. Find the shape of the array
Determine the number of rows and the number of columns.
2. Calculate the average of each parameter

3. Find the maximum and minimum temperature


4. Extract the voltage column


5. Identify high-temperature readings


6. Identify low battery readings


In [41]:
import numpy as np


data_matrix = np.array([
    [d['Temperature'], d['Voltage'], d['Current'], d['Charge']]
    for d in combined_sensor_data
])

In [42]:
array_shape = data_matrix.shape
print(f"\n1. Shape of the array: {array_shape} (rows, columns)")


averages = np.mean(data_matrix, axis=0)
print("\n2. Average of each parameter:")
print(f"   Average Temperature (T̄): {averages[0]:.2f}°C")
print(f"   Average Voltage (V̄): {averages[1]:.2f}")
print(f"   Average Current (Ī): {averages[2]:.2f}")
print(f"   Average Charge (C̄): {averages[3]:.2f}%")



1. Shape of the array: (6, 4) (rows, columns)

2. Average of each parameter:
   Average Temperature (T̄): 38.67°C
   Average Voltage (V̄): 387.50
   Average Current (Ī): 26.17
   Average Charge (C̄): 73.50%


In [43]:
temperatures = data_matrix[:, 0]
t_max = np.max(temperatures)
t_min = np.min(temperatures)
print(f"\n3. Maximum Temperature (T_max): {t_max}°C")
print(f"   Minimum Temperature (T_min): {t_min}°C")


voltage_column = data_matrix[:, 1]
print("\n4. Extracted Voltage Column:")
print(voltage_column)



3. Maximum Temperature (T_max): 45°C
   Minimum Temperature (T_min): 32°C

4. Extracted Voltage Column:
[400 395 390 385 380 375]


In [44]:
high_temp_readings = data_matrix[data_matrix[:, 0] > 40]
print("\n5. Rows with High Temperature (T > 40 °C):")
if high_temp_readings.size > 0:
    print(high_temp_readings)
else:
    print("No high temperature readings found.")


low_battery_readings = data_matrix[data_matrix[:, 3] < 50]
print("\n6. Rows with Low Battery (C < 50 %):")
if low_battery_readings.size > 0:
    print(low_battery_readings)
else:
    print("No low battery readings found.")


5. Rows with High Temperature (T > 40 °C):
[[ 42 380  30  60]
 [ 45 375  32  48]]

6. Rows with Low Battery (C < 50 %):
[[ 45 375  32  48]]


## Task 3 — Analysis Using Linear Algebra

In [45]:
import numpy as np

A = np.array([
    [2, 1],
    [1, 3]
])


X = np.array([
    [40],
    [25]
])

print("Task 3: Battery Stress Index Calculation (Y = A X)")
print("---------------------------------------------------")
print("Transformation Matrix A:")
print(A)
print("\nSensor Input Vector X:")
print(X)


Y = np.dot(A, X)
print("\nResulting Vector Y (Battery Stress Index):")
print(Y)


Task 3: Battery Stress Index Calculation (Y = A X)
---------------------------------------------------
Transformation Matrix A:
[[2 1]
 [1 3]]

Sensor Input Vector X:
[[40]
 [25]]

Resulting Vector Y (Battery Stress Index):
[[105]
 [115]]


### Additional Linear Algebra Tasks for Matrix A

In [46]:

A_transpose = A.T
print("1. Transpose of A (Aᵀ):")
print(A_transpose)


A_determinant = np.linalg.det(A)
print(f"\n2. Determinant of A (det(A)): {A_determinant:.2f}")


if A_determinant != 0:
    A_inverse = np.linalg.inv(A)
    print("\n3. Inverse of A (A⁻¹):")
    print(A_inverse)
else:
    print("\n3. Inverse does not exist (determinant is zero).")


1. Transpose of A (Aᵀ):
[[2 1]
 [1 3]]

2. Determinant of A (det(A)): 5.00

3. Inverse of A (A⁻¹):
[[ 0.6 -0.2]
 [-0.2  0.4]]


### Solving a System of Equations (A X = B)

In [47]:
B = np.array([
    [100],
    [120]
])

print("System of Equations: A X = B")
print("Matrix A:")
print(A)
print("\nVector B:")
print(B)


if np.linalg.det(A) != 0:
    solution_X = np.linalg.solve(A, B)
    print("\nSolution for X (x, y) using np.linalg.solve:")
    print(solution_X)
    print(f"Therefore, x = {solution_X[0][0]:.2f} and y = {solution_X[1][0]:.2f}")
else:
    print("\nCannot solve the system of equations (matrix A is singular).")


System of Equations: A X = B
Matrix A:
[[2 1]
 [1 3]]

Vector B:
[[100]
 [120]]

Solution for X (x, y) using np.linalg.solve:
[[36.]
 [28.]]
Therefore, x = 36.00 and y = 28.00


## Task 4 — Analysis Using Calculus

In [48]:
from sympy import symbols, diff

# Define the symbolic variable t
t = symbols('t')

# Define the battery charge function C(t)
C_t = 100 - 2*t - (1/2)*t**2

print("Battery Charge Function C(t):")
print(C_t)


Battery Charge Function C(t):
-0.5*t**2 - 2*t + 100


In [49]:
# 1. Find the rate of change of battery charge (dC/dt)
dC_dt = diff(C_t, t)

print("1. Rate of Change of Battery Charge (dC/dt):")
print(dC_dt)


1. Rate of Change of Battery Charge (dC/dt):
-1.0*t - 2


In [50]:
# 2. Calculate the discharge rate at t = 2 and t = 5
discharge_rate_t2 = dC_dt.subs(t, 2)
discharge_rate_t5 = dC_dt.subs(t, 5)

print("2. Discharge Rate Calculations:")
print(f"   dC/dt at t = 2 hours: {discharge_rate_t2}")
print(f"   dC/dt at t = 5 hours: {discharge_rate_t5}")


2. Discharge Rate Calculations:
   dC/dt at t = 2 hours: -4.00000000000000
   dC/dt at t = 5 hours: -7.00000000000000


### 4.3. Interpretation of the Result

- At `t = 2` hours, the rate of change of battery charge is `-4` %/hour.
- At `t = 5` hours, the rate of change of battery charge is `-7` %/hour.

Since the absolute value of the discharge rate (`|dC/dt|`) is increasing over time (from 4 to 7), this indicates that the **battery is losing charge at an increasing rate**.

## Final Analysis and Decision - Battery Performance Report

In [51]:
print("1. Safety")
# Find the first time temperature exceeds 40 °C
first_high_temp_time = None
for reading in combined_sensor_data:
    if reading['Temperature'] > 40:
        first_high_temp_time = reading['Time']
        break

if first_high_temp_time is not None:
    print(f"   The temperature first exceeds 40 °C at Time = {first_high_temp_time} hours.")
else:
    print("   Temperature never exceeded 40 °C.")

print("\n2. Battery Charge")
# Calculate total charge reduction
initial_charge = combined_sensor_data[0]['Charge']
final_charge = combined_sensor_data[-1]['Charge']
charge_loss = initial_charge - final_charge
print(f"   Initial Charge (C_initial): {initial_charge}%")
print(f"   Final Charge (C_final): {final_charge}%")
print(f"   Total Charge Reduction (Charge Loss = C_initial - C_final): {charge_loss}%")

print("\n3. NumPy Analysis")
print(f"   Average Temperature (T̄): {averages[0]:.2f}°C")
print(f"   Average Voltage (V̄): {averages[1]:.2f}")
print(f"   Average Current (Ī): {averages[2]:.2f}")
print(f"   Average Charge (C̄): {averages[3]:.2f}%")

print("\n4. Linear Algebra")
print("   Transformed Output Y = AX:")
print(Y)
print(f"   Solution for AX = B: x = {solution_X[0][0]:.2f}, y = {solution_X[1][0]:.2f}")

print("\n5. Calculus")
print(f"   Rate of change of battery charge (dC/dt) at t=2h: {dC_dt.subs(t, 2)}")
print(f"   Rate of change of battery charge (dC/dt) at t=5h: {dC_dt.subs(t, 5)}")
print("   Interpretation: The absolute value of the discharge rate is increasing over time, indicating the battery is losing charge at an increasing rate.")


1. Safety
   The temperature first exceeds 40 °C at Time = 4 hours.

2. Battery Charge
   Initial Charge (C_initial): 95%
   Final Charge (C_final): 48%
   Total Charge Reduction (Charge Loss = C_initial - C_final): 47%

3. NumPy Analysis
   Average Temperature (T̄): 38.67°C
   Average Voltage (V̄): 387.50
   Average Current (Ī): 26.17
   Average Charge (C̄): 73.50%

4. Linear Algebra
   Transformed Output Y = AX:
[[105]
 [115]]
   Solution for AX = B: x = 36.00, y = 28.00

5. Calculus
   Rate of change of battery charge (dC/dt) at t=2h: -4.00000000000000
   Rate of change of battery charge (dC/dt) at t=5h: -7.00000000000000
   Interpretation: The absolute value of the discharge rate is increasing over time, indicating the battery is losing charge at an increasing rate.


### 6. Final Decision

**MONITOR — The battery requires continuous monitoring.**

### Final Discussion Question

Based on the analysis, several factors indicate that the battery may become unsafe or requires careful attention:

*   **High Temperature Alerts:** The temperature exceeded 40 °C at 4 hours into the test, reaching 42°C and 45°C. Prolonged or extreme high temperatures can degrade battery life and pose safety risks.
*   **Increasing Discharge Rate:** This suggests that the battery's efficiency is worsening over time, and it's losing charge more rapidly towards the end of the test.


To improve battery performance monitoring, additional data that would be valuable includes:

*   **Cycle Life Data:** Recording the number of charge/discharge cycles and the capacity fade over these cycles would give a clearer picture of the battery's long-term durability.
*   **Environmental Conditions:** More detailed environmental data  could help differentiate between battery-specific issues and external influences.
